spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/pet_house?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: pet_user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true