server:
  port: 8686

spring:
<<<<<<< HEAD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/pet_house?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: pet_user
    password: 1234
=======
  application:
    name: animal

  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
>>>>>>> b430d7e75ca27783e2c1ba8cb0e646135cbb3a60

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD
    properties:
      hibernate:
        format_sql: true
=======
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: z7v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVm
  expiration: 86400000

logging:
  level:
    org.hibernate.SQL: debug

file:
  path: ${user.dir}/uploads/image
>>>>>>> b430d7e75ca27783e2c1ba8cb0e646135cbb3a60
