server:
  port: 8686

spring:
  application:
    name: animal
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_house?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: pet_user
    password: 1234  

  # datasource:
  #   url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: root
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect    #MySQL8Dialect , H2Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: z7v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVm
  expiration: 86400000

logging:
  level:
    org.hibernate.SQL: debug

file:
  path: ${user.dir}/uploads/image
